# Generated by Django 4.0.5 on 2022-07-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
