# Generated by Django 4.0.5 on 2022-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_user_id_carmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='used_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
