# Generated by Django 4.0.5 on 2022-07-09 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_used_car_alter_carmodel_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{5,20}$', ['Something went wrong, your name can`t contain numbers or other non-alphabetic symbols'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_name',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{5,20}$', ['Something went wrong, your name can`t contain numbers or other non-alphabetic symbols'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_series',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{5,20}$', ['Something went wrong, your name can`t contain numbers or other non-alphabetic symbols'])]),
        ),
    ]
