# Generated by Django 4.0.5 on 2022-07-06 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparksmodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{5,20}$', ['Something went wrong, your name can`t contain numbers or other non-alphabetic symbols'])]),
        ),
    ]
